default:
  image: registry.sxxfuture.net/lib/docker/lotus-builder/debian:230224-002040

stages:
  - build

.build-snippet:
  tags: [docker, x86, merak]
  stage: build
  variables:
    GIT_STRATEGY: clone
    GOPATH: $CI_PROJECT_DIR/.go
    HTTP_PROXY: $DEFAULT_PROXY
    HTTPS_PROXY: $DEFAULT_PROXY
    http_proxy: $DEFAULT_PROXY
    https_proxy: $DEFAULT_PROXY
    RUSTFLAGS: ""
    GOFLAGS: ""
  cache:
    - key:
        files:
          - go.mod
          - go.sum
      paths:
        - .go/
  before_script:
    - mkdir -p .go

include:
  - '.gitlab-ci/v20-filbase-playground.yml'
